### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by 2682856025** [haojiezhe12345/vocabgo-auto#2]
-> POST https://app.vocabgo.com/studentv1/api/Student/ClassTask/VerifyAnswer
{
  "answer": "bid,sb,do,sth",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5KTaWmabmKSlWRqamSVbmNrcWdpbmubkGdgkpNqbG6bbXFmXGlrbZKZZmScbGJpa2tqam+WZGeT"
}
<- 200
{
  "word": "bid",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5KTaWmabmKSk1qbm5yOq5linKVlqanNhpORjZRxYGqYYW5qYWhubJiNZVyWZWdvb3Fxam2OaWxtaG5ramyckGhnlJRxa2uOZZY=",
  "over_status": 2,
  "answer_result": 2,
  "clean_status": 1,
  "answer_corrects": []
}
ERROR getting answer!

**Comment by 2682856025** [comment]
总是循环这一部分 卡住了
-> POST https://app.vocabgo.com/studentv1/api/Student/ClassTask/VerifyAnswer
{
  "answer": "",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSlWRqaWSVamNrcWdpbmubkGdgkpNqbG6bbXFmXGlrbZKZZ2SXaWJpa2tqam+WZGeT"
}
<- 200
{
  "word": "bid",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSk1pbj5WOaW5ia2hla26WlG5ql49qYGiSZnFoaXBua46SaWeVbWlramxlZGuVaW9tbGJpkw==",
  "over_status": 2,
  "answer_result": 2,
  "clean_status": 1,
  "answer_corrects": []
}

-> POST https://app.vocabgo.com/studentv1/api/Student/ClassTask/VerifyAnswer
{
  "answer": "",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSk1pbj5WOaW5ia2hla26WlG5ql49qYGiSZnFoaXBua46SaWeVbWlramxlZGuVaW9tbGJpkw=="
}
<- 200
{
  "word": "bid",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSk1pbj2S9WlmTlWJqbWGYlmJpmpRpbG2YYWpdYWhnbpmabGiaYWdsb2hxZWyUbGNoa2lqbmyZkGaR",
  "over_status": 1,
  "answer_result": 2,
  "clean_status": 2,
  "answer_corrects": [
    "bid sb. do sth."
  ]
}

-> POST https://app.vocabgo.com/studentv1/api/Student/ClassTask/VerifyAnswer
{
  "answer": "bid,sb,do,sth",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSlWRqaWSVamNrcWdpbmubkGdgkpNqbG6bbXFmXGlrbZKZZ2SXaWJpa2tqam+WZGeT"
}
<- 200
{
  "word": "bid",
  "topic_code": "kFt7epdqWI6DfnrEaZVtl2pbXlrEoZtYZGlrYmaWmG9ljb5blqDGYayTXmSapY7UqJiTV5Njk1qbm5yCq5lkWJqoVqjZzGRWvo9qYGiOZnBiZ2xvZ5iWbGCabmKSk1qbm5yOq5linKVlqanNhpORjZRwYGqUYW5qYWhubJiNZVyWZWdvb3Fxam2OaWxtaG5sameZkGhnlJRxa2uOZZY=",
  "over_status": 2,
  "answer_result": 2,
  "clean_status": 1,
  "answer_corrects": []
}
ERROR getting answer!

**Comment by haojiezhe12345** [comment]
https://github.com/haojiezhe12345/vocabgo-auto/commit/a4d5cc628b7ccc08fb1cbcb406e5ba857405ee6a
